### ISSUE TITLE
Añadir la suma de las horas de sol a las climate_aggregations y los datos de la estación de la que son los datos (y otros)

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#112]
- [x] Datos de la estación como mínimo el nombre aunque sería interesante tener todos sus datos y la distancia a la parcela (esa también la puedo sacar yo)
- [ ] Número de días de lluvia del último año
- [x] Suma de las horas de sol del último año
- [ ] Cuando esté la parte JS, eliminar las medidas mensuales
- [x] Los datos de temperatura, sol y radiación son diarios, con mensuales las gráficas quedan un poco sosas creo:
![image](https://cloud.githubusercontent.com/assets/8138049/19412115/f0675460-930e-11e6-803e-da589708c5a9.png)

![image](https://cloud.githubusercontent.com/assets/8138049/19412123/1b1b4f36-930f-11e6-9ac1-a3e209727e57.png)

**Comment by jlafuentegarcia** [comment]
Pueeees, ¿no crees que se ve mejor por mes?

**Comment by teanocrata** [comment]
Hombre, pues se ve que en verano hace más calor que en invierno, pero entiendo que es más interesante ver que aunque hace calor puede haber días con diferencias importantes de temperaturas o heladas o cosas así, jeje. Pero vamos, que igualmente no se si realmente da información interesante o no, pero parece más chulo con más líneas jaja

**Comment by jlafuentegarcia** [comment]
OK OK, pues por día será. O por semana, que a lo mejor es mejor. Probamos

**Comment by jlafuentegarcia** [comment]
Ya me gustaría a mí saber cómo ibas a sacar la distancia, ya... :-P

**Comment by jlafuentegarcia** [comment]
Que lo digo por el javascript, ¿eh? Que a ver si ibas a calcular la distancia sin tener en cuenta la curvatura de la tierra :-)))))

**Comment by jlafuentegarcia** [comment]
Por cierto, si me hicieras una pequeña query en elasticsearch para lo de los días de lluvia esos del año, pues me ahorrarías un tener que aprender (que algún día lo haré, pero ahora no es el momento :-) )

**Comment by teanocrata** [comment]
Ahora te la paso, el caso es que las había puesto en alguna issue y ahora no se dónde están jaja, ahora te las paso

**Comment by teanocrata** [comment]
Ahora lo formateo, creo que es esta:
{
   "size" : 0,
   "query" : {
        "constant_score" : {
            "filter" : {
              "bool": { 
                "must": [
                  { "term": { "IDESTACION" : "' . $estacion ["IDESTACION"] . '" } },
                  { "term": { "IDPROVINCIA" : "' . $estacion ["IDPROVINCIA"] . '" } } 
                ]
              }
            }
        }
    },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO",
              "order": {
                "_term" : "desc" 
              },
             "size": ' . $numeroDeAnios . '
         },
         "aggs": { 
            "medida": { 
               "date_histogram": {
                  "field": "FECHA",
                  "interval": "' . $intervalo . '",
                  "format": "' . $formato . '" 
               },
               "aggs": {
                  "medida": {
                     "sum": { "field": "' . $medida . '"} 
                  }
               }
            }
         }
      }
   }
}

**Comment by teanocrata** [comment]
## Estación más cercana a unas coordenadas con distancia en km:
`
GET /inforiego/info_riego_station/_search
{
   "size": 1,
   "sort": [
      {
         "_geo_distance": {
            "lat_lon": {
               "lat": 40.439983,
               "lon": -5.737026
            },
            "order": "asc",
            "unit": "km",
            "mode": "min",
            "distance_type": "sloppy_arc"
         }
      }
   ]
}
`

## Suma de las precipitaciones para un año:
`
GET /inforiego/info_riego_daily/_search
{
   "size": 0,
   "query": {
      "constant_score": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "range": {
                        "PRECIPITACION": {
                           "gt": 0
                        }
                     }
                  },
                  {
                     "term": {
                        "IDESTACION": "102"
                     }
                  },
                  {
                     "term": {
                        "IDPROVINCIA": "5"
                     }
                  },
                  {
                     "term": {
                        "AÑO": "2016"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO"
         },
         "aggs": {
            "sum_precipitacion": {
               "sum": {
                  "field": "PRECIPITACION"
               }
            }
         }
      }
   }
}
`

## Agregados del resto de cosas:
`
GET /inforiego/info_riego_daily/_search
{"size" : 0,
   "query" : {
        "constant_score" : {
            "filter" : {
              "bool": {
                "must": [
                  { "term": { "IDESTACION" : "4" } },
                  { "term": { "IDPROVINCIA" : "49" } },
                  { "term": { "AÑO" : "2016" } }
                ]
              }
            }
        }
    },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO"
         },
         "aggs":  {
            "max_temperatura": { 
               "max": {
                  "field": "TEMPMAX" 
               }
            },
            "min_temperatura": { 
               "min": {
                  "field": "TEMPMIN" 
               }
            },
            "media_temperatura": { 
               "avg": {
                  "field": "TEMPMEDIA" 
               }
            },
            "media_horas_sol": { 
               "avg": {
                  "field": "N" 
               }
            },
            "max_horas_sol": { 
               "max": {
                  "field": "N" 
               }
            },
            "sum_horas_sol": { 
               "sum": {
                  "field": "N" 
               }
            },
            "media_radiacion": { 
               "avg": {
                  "field": "RADIACION" 
               }
            },
            "max_radiacion": { 
               "max": {
                  "field": "RADIACION" 
               }
            },
            "sum_radiacion": { 
               "sum": {
                  "field": "RADIACION" 
               }
            }          
         }
      }
   }
}
`
## Precipitaciones por meses:
`
GET inforiego/info_riego_daily/_search
{
   "size": 0,
   "query": {
      "constant_score": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "IDESTACION": "102"
                     }
                  },
                  {
                     "term": {
                        "IDPROVINCIA": "5"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO",
            "order": {
               "_term": "desc"
            },
            "size": 3
         },
         "aggs": {
            "medida": {
               "date_histogram": {
                  "field": "FECHA",
                  "interval": "month",
                  "format": "M"
               },
               "aggs": {
                  "medida": {
                     "sum": {
                        "field": "PRECIPITACION"
                     }
                  }
               }
            }
         }
      }
   }
}
`
## Temperaturas diarias:
`
GET inforiego/info_riego_daily/_search
{
   "size": 0,
   "query": {
      "constant_score": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "IDESTACION": "102"
                     }
                  },
                  {
                     "term": {
                        "IDPROVINCIA": "5"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO",
            "order": {
               "_term": "desc"
            },
            "size": 3
         },
         "aggs": {
            "medida": {
               "date_histogram": {
                  "field": "FECHA",
                  "interval": "day",
                  "format": "DDD"
               },
               "aggs": {
                  "medida": {
                     "sum": {
                        "field": "TEMPERATURA"
                     }
                  }
               }
            }
         }
      }
   }
}
`
## Número de horas de sol diarias
`
GET inforiego/info_riego_daily/_search
{
   "size": 0,
   "query": {
      "constant_score": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "IDESTACION": "102"
                     }
                  },
                  {
                     "term": {
                        "IDPROVINCIA": "5"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO",
            "order": {
               "_term": "desc"
            },
            "size": 3
         },
         "aggs": {
            "medida": {
               "date_histogram": {
                  "field": "FECHA",
                  "interval": "day",
                  "format": "DDD"
               },
               "aggs": {
                  "medida": {
                     "sum": {
                        "field": "N"
                     }
                  }
               }
            }
         }
      }
   }
}
`

## Radiación diaria:
`
GET inforiego/info_riego_daily/_search
{
   "size": 0,
   "query": {
      "constant_score": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "IDESTACION": "102"
                     }
                  },
                  {
                     "term": {
                        "IDPROVINCIA": "5"
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "anios": {
         "terms": {
            "field": "AÑO",
            "order": {
               "_term": "desc"
            },
            "size": 3
         },
         "aggs": {
            "medida": {
               "date_histogram": {
                  "field": "FECHA",
                  "interval": "day",
                  "format": "DDD"
               },
               "aggs": {
                  "medida": {
                     "sum": {
                        "field": "RADIACION"
                     }
                  }
               }
            }
         }
      }
   }
}
`
