### ISSUE TITLE
Error al obtener las parcelas por bbox

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#115]
Con la siguiente url por ejemplo:
http://89.141.96.206:8000/osc/cadastral/parcel?bbox=40.436907,-5.742514,40.440655,-5.735739

Se obtiene lo siguiente

`
IndexError at /osc/cadastral/parcel
list index out of range
Request Method:	GET
Request URL:	http://89.141.96.206:8000/osc/cadastral/parcel?bbox=40.436907,-5.742514,40.440655,-5.735739
Django Version:	1.10.2
Exception Type:	IndexError
Exception Value:	
list index out of range
Exception Location:	/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/polyline/codec.py in encode, line 54
Python Executable:	/opt/anaconda2/envs/opensmartcountry-env/bin/python
Python Version:	2.7.12
Python Path:	
['/home/osc/GitHub/OpenSmartCountry/Django/osc_site',
 '/home/osc/GitHub/OpenSmartCountry/Django/osc_site',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python27.zip',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/plat-linux2',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/lib-tk',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/lib-old',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/lib-dynload',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg',
 '/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages']
Server time:	Sat, 15 Oct 2016 10:51:33 +0200
`

Más info:
`
Environment:

Request Method: GET
Request URL: http://89.141.96.206:8000/osc/cadastral/parcel?bbox=40.436907,-5.742514,40.440655,-5.735739

Django Version: 1.10.2
Python Version: 2.7.12
Installed Applications:
['osc.apps.OscConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_cron']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/osc/GitHub/OpenSmartCountry/Django/osc_site/osc/views/cadastre.py" in obtain_catastral_parcels
  67.         elevations = obtain_elevation_from_google(centers)

File "/home/osc/GitHub/OpenSmartCountry/Django/osc_site/osc/services/google.py" in obtain_elevation_from_google
  24.                                          'locations': compose_locations_param(centers)})

File "/home/osc/GitHub/OpenSmartCountry/Django/osc_site/osc/services/google.py" in compose_locations_param
  12.     param = polyline.encode(points)

File "/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/polyline/__init__.py" in encode
  27.     return PolylineCodec().encode(coordinates, precision)

File "/opt/anaconda2/envs/opensmartcountry-env/lib/python2.7/site-packages/polyline/codec.py" in encode
  54.         self._write(output, coordinates[0][0], 0, factor)

Exception Type: IndexError at /osc/cadastral/parcel
Exception Value: list index out of range
`

**Comment by teanocrata** [comment]
El bbox está al revés, corregir en el código

**Comment by jlafuentegarcia** [comment]
Por cierto, ¿prefieres lon,lat o lat,lon?

**Comment by teanocrata** [comment]
Lat lon porque el api de Google tiene un tourl que lo pasa con lat lon, pero en realidad me da igual, como prefieras

**Comment by jlafuentegarcia** [comment]
Pues lat, lon. Así se queda.

Lo raro es que luego en todo lo demás geojson devuelvo lon lat

**Comment by teanocrata** [comment]
Vi un artículo al respecto sobre que y porque se usaba lon lat o lat lon, Google usa lat lon siempre pero trabaja bien con geojson, es decir si no es geojson es lat lon, si es geojson es lon lat, luego lo busco
