### ISSUE TITLE
Controlar cuando no devuelve parcelas para que no de un error al conseguir elevations

### ISSUE THREAD

**Issue by jlafuentegarcia** [teanocrata/OpenSmartCountry#116]

**Comment by teanocrata** [comment]
Creo que da error en más casos, no se si es que está fallando lo de obtener las elevations o nos hemos pasado ya de la cota o algo así. Por ejemplo está fallando esto:
http://89.141.96.206:8000/osc/cadastral/parcel?cadastral_code=40167A00709002&retrieve_public_info=True&retrieve_climate_info=True

**Comment by jlafuentegarcia** [comment]
No no, el fallo lo da al montar la lista de puntos, creo. Me da que va vacío, pero lo miro en un plis
