### ISSUE TITLE
Si se produce algún error al pedir datos es necesario que nos enteremos

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#120]
Por ejemplo ahora mismo al pedir por bbox llega siempre una lista vacía pero no se si es porque el bbox no contiene nada, está mal formado, o he superado el número de peticiones al catastro con lo que no se si tengo que esperar o tengo algo mal.

**Comment by jlafuentegarcia** [comment]
Jejeje era consciente, sí.
