### ISSUE TITLE
Servicios para datos de los cultivos

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#121]
Ahora mismo existe un servicio que da los cultivos paginados y que los filtra con respecto a ciertas condiciones.

De momento sigue funcionando a través de php que actúa simplemente para puentar el tema del cros domain, es decir que punciona haciendo la misma petición que se hace desde js pero a través de php, funciona con get, post, con querystring y con inputs (o data o como se llame)

Va contra el index osc

**Comment by jlafuentegarcia** [comment]
Ay la leche, y ¿qué peticiones se hacen?

**Comment by teanocrata** [comment]
pues las que pone en el texto, ¿o no se entiende que puntiona es funciona, que puentar es puentear  y que los inputs o data o lo que sea es eso que no va en la url pero se envía? Jeje, ¿se puede hacer algo así con django o es mejor pensar un poco más el tipo de cosas que se piden?

**Comment by jlafuentegarcia** [comment]
Pues molaría especificar, sí, aunque se puede puentear también
Pero eso nos acoplaría a Elastic, y la idea es que no... 

Normalmente, ¿por qué criterios buscas los cultivos?
