### ISSUE TITLE
Si la parcela es compuesta, no pilla bien las properties al hacer click en ella

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#122]
En Sanchotello la que queda justo al norte es un buen ejemplo. La parcela debe tener varios cultivos distintos, cuando la pinto en el mapa se ven varias, cuando la pinto por referencia catastral en el perfil una, es más, creo que no acaba de pintar todo el perfil:
![image](https://cloud.githubusercontent.com/assets/8138049/19427600/4ef7cfaa-9445-11e6-9703-5d82d0cb4abb.png)
![image](https://cloud.githubusercontent.com/assets/8138049/19427664/ba5566d6-9445-11e6-92e1-b9e9c688937e.png)

**Comment by jlafuentegarcia** [comment]
A ver, el tema es el siguiente:

Esta llamada http://ovc.catastro.meh.es/ovcservweb/OVCSWLocalizacionRC/OVCCallejero.asmx/Consulta_DNPRC?Provincia=&Municipio=&RC=37284A016001460000

Devuelve algo distinto de esta otra:
http://ovc.catastro.meh.es/ovcservweb/OVCSWLocalizacionRC/OVCCallejero.asmx/Consulta_DNPRC?Provincia=&Municipio=&RC=37284A01600146

Mientras que esta: http://ovc.catastro.meh.es/INSPIRE/wfsCP.aspx?service=wfs&request=getfeature&STOREDQUERIE_ID=GetParcel&REFCAT=37284A016001460000&srsname=EPSG::25830

Da exactamente lo mismo que esta otra: http://ovc.catastro.meh.es/INSPIRE/wfsCP.aspx?service=wfs&request=getfeature&STOREDQUERIE_ID=GetParcel&REFCAT=37284A01600146&srsname=EPSG::25830

De cara a pintar, da exactamente el mismo resultado, eso si... ¿no?

Es decir, mi pregunta es: ¿cómo podría llegar un usuario a la de los 0000?

**Comment by teanocrata** [comment]
Efectivamente el usuario hoy por hoy  no puede llegar a la de los 0000.

La primera devuelve la información catastral con respecto los cultivos de la 0000

La segunda en realidad dice que hay dos  cosas del tipo de la primera, la 0000 y la 0001

La tercera tiene la información de la geometría de la ¿segunda?

El problema es que para pintar el perfil necesitamos la información de los 0000 o 0001 (tengo que pintar bien cada una para poder decir un poco más) y ahora no podemos acceder a ella

**Comment by jlafuentegarcia** [comment]
Pero el problema, @teanocrata, es que desde el punto de vista del inspire la parcela sin los 0000 no es compuesta. Es decir, devuelve un solo perímetro: ¿tú por qué sabes que geográficamente sí lo es?

**Comment by teanocrata** [comment]
Claro, justo ese es el problema, que yo me doy cuenta de que es compuesta cuando intento pintar su perfil con la referencia catastral porque  ( y aquí aparece un problema más)  cuando las pinto puedo selecciona cualquiera de los recintos y me dan la misma referencia catastral (sin los 0000):
![image](https://cloud.githubusercontent.com/assets/8138049/19588403/dee7730e-9765-11e6-8515-880418cfa7ca.png)

Y cuando pido su perfil por esa referencia catastral lo que me devuelve no es la información de los cultivos (que está en el 0000) si no la del suelo sin edificar:
`cadastralData: {
control: {
cudnp: 2
},
lrcdnp: {
rcdnp: {
dt: {
np: "SALAMANCA",
locs: {
lous: {
lorus: {
cpp: {
cpa: 146,
cpo: 16
},
czc: 0,
npa: "PE¥A FRAILES",
cpaj: 181
},
lourb: {
loint: null,
dir: {
tv: "NC",
cv: "NC",
nv: "NC"
}
}
}
},
loine: {
cp: 37,
cm: 282
},
cmc: 284,
nm: "SANCHOTELLO"
},
rc: {
pc2: 1600146,
car: 1,
pc1: "37284A0",
cc1: "S",
cc2: "M"
}
}
}
}`

**Comment by teanocrata** [comment]
El otro problema es la especie de  circulito que hay ahí arriba que en el catastro no existe pero esto puede ser simplemente por usar los datos de sigpac y en cuanto usemos los del catastro se resuelva

**Comment by jlafuentegarcia** [comment]
Jeje ya sé qué pasa.

Mi mini método xml2json es una mierda pinchada en un palo. Eso sí, súper sencillo :-)
