### ISSUE TITLE
Prepara el nuevo servidor

### ISSUE THREAD

**Issue by teanocrata** [teanocrata/OpenSmartCountry#126]
- [x] ¿Máquinas virtuales?
- [x] Docker
- [x] Elastic
- [x] Kibana
- [x] Marvel
- [x] Django + servidor
- [ ] PHP + servidor
- [x] Acceso, cuentas, etc.
- [x] Securización de elastic

**Comment by teanocrata** [comment]
Tema de generar dockersfiles específicos: https://github.com/docker-library/docs/blob/master/README.md

**Comment by jlafuentegarcia** [comment]
Perooooooo, PHP para qué?

**Comment by teanocrata** [comment]
Para hacer el cambio en caso de que sea necesario, vamos que depende de cómo nos organicemos lo meto o no
